# Generated by Django 4.0.4 on 2022-05-13 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlmanager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urldata',
            old_name='big_link',
            new_name='link',
        ),
    ]
